/**
 * Artifact Viewer — renders AI-generated visual content in chat
 *
 * Supports HTML (sandboxed iframe), SVG (inline), and Mermaid (rendered via CDN).
 * Features: code/preview toggle, copy code, auto-resize, open in new tab.
 *
 * Security: HTML artifacts run in sandboxed iframes (allow-scripts only, no
 * allow-same-origin). SVG is rendered inline as it's generated by the AI in
 * the user's authenticated session — same trust model as claude.ai artifacts.
 */
import { useState, useRef, useEffect } from 'react'
import { Code2, Eye, Copy, Check, ExternalLink } from 'lucide-react'
import { cn } from '@/lib/utils'

interface ArtifactData {
  _artifact: true
  type: 'html' | 'svg' | 'mermaid'
  title: string
  code: string
  height?: number
  artifactId?: string
}

export function isArtifact(output: unknown): output is ArtifactData {
  return !!output && typeof output === 'object' && (output as Record<string, unknown>)['_artifact'] === true
}

interface Props {
  artifact: ArtifactData
}

export function ArtifactViewer({ artifact }: Props) {
  const [showCode, setShowCode] = useState(false)
  const [copied, setCopied] = useState(false)
  const [autoHeight, setAutoHeight] = useState<number | null>(null)
  const iframeRef = useRef<HTMLIFrameElement>(null)

  const height = autoHeight || artifact.height || 400

  useEffect(() => {
    const handler = (e: MessageEvent) => {
      if (e.source !== iframeRef.current?.contentWindow) return
      if (e.data?.type === 'artifact-resize' && typeof e.data.height === 'number') {
        setAutoHeight(Math.min(e.data.height + 2, 800))
      }
    }
    window.addEventListener('message', handler)
    return () => window.removeEventListener('message', handler)
  }, [])

  const handleCopy = () => {
    navigator.clipboard.writeText(artifact.code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const iframeSrc = buildIframeSrc(artifact)

  return (
    <div className="my-2 rounded-lg border border-border overflow-hidden">
      <div className="flex items-center justify-between px-3 py-1.5 bg-muted/50 border-b border-border">
        <div className="flex items-center gap-2 min-w-0">
          <span className="text-xs font-medium truncate">{artifact.title}</span>
          <span className="text-[10px] text-muted-foreground uppercase">{artifact.type}</span>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={() => setShowCode(!showCode)}
            className={cn('p-1 rounded text-muted-foreground hover:text-foreground transition-colors', showCode && 'bg-muted text-foreground')}
            title={showCode ? 'Show preview' : 'Show code'}
          >
            {showCode ? <Eye className="size-3.5" /> : <Code2 className="size-3.5" />}
          </button>
          <button onClick={handleCopy} className="p-1 rounded text-muted-foreground hover:text-foreground transition-colors" title="Copy code">
            {copied ? <Check className="size-3.5 text-green-500" /> : <Copy className="size-3.5" />}
          </button>
          {artifact.type === 'html' && (
            <button
              onClick={() => {
                const blob = new Blob([artifact.code], { type: 'text/html' })
                window.open(URL.createObjectURL(blob), '_blank')
              }}
              className="p-1 rounded text-muted-foreground hover:text-foreground transition-colors"
              title="Open in new tab"
            >
              <ExternalLink className="size-3.5" />
            </button>
          )}
        </div>
      </div>

      {showCode ? (
        <pre className="p-3 text-xs font-mono overflow-auto max-h-96 bg-background">{artifact.code}</pre>
      ) : (
        <div className="bg-muted/50 dark:bg-[#0f1117]">
          {artifact.type === 'svg' ? (
            <SvgRenderer code={artifact.code} height={height} />
          ) : (
            <iframe
              ref={iframeRef}
              srcDoc={iframeSrc}
              sandbox="allow-scripts"
              style={{ width: '100%', height: `${height}px`, border: 'none' }}
              title={artifact.title}
            />
          )}
        </div>
      )}
    </div>
  )
}

/** Render SVG safely via an iframe to avoid script injection */
function SvgRenderer({ code, height }: { code: string; height: number }) {
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const html = `<!DOCTYPE html><html><head><style>body{margin:0;padding:16px;background:#0f1117;display:flex;justify-content:center;align-items:center;min-height:100vh;}</style></head><body>${code}</body></html>`
  return (
    <iframe
      ref={iframeRef}
      srcDoc={html}
      sandbox="allow-scripts"
      style={{ width: '100%', height: `${height}px`, border: 'none' }}
      title="SVG artifact"
    />
  )
}

function buildIframeSrc(artifact: ArtifactData): string {
  const resizeScript = `<script>new ResizeObserver(()=>{parent.postMessage({type:'artifact-resize',height:document.documentElement.scrollHeight},'*')}).observe(document.documentElement)<\/script>`

  if (artifact.type === 'mermaid') {
    return `<!DOCTYPE html>
<html><head>
<style>body{margin:0;padding:16px;background:#0f1117;color:#e2e8f0;font-family:system-ui;display:flex;justify-content:center;}</style>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"><\/script>
</head><body>
<pre class="mermaid">${escapeHtml(artifact.code)}</pre>
<script>mermaid.initialize({startOnLoad:true,theme:'dark'});<\/script>
${resizeScript}
</body></html>`
  }

  // HTML — inject resize script
  if (artifact.code.includes('</body>')) {
    return artifact.code.replace('</body>', `${resizeScript}</body>`)
  }
  return artifact.code + resizeScript
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
